### ISSUE TITLE
SimpleIDE: No print dialog from File -> Print

### ISSUE THREAD

**Issue by GoogleCodeExporter** [parallaxinc/propside#237]
```
A) What steps will reproduce the problem?

  1. Open a program with SimpleIDE
  2. Click File and select Print

B) What is the expected and actual behavior (output)?

  Expected: Print dialog appears.
  Actual: Nothing seems to happen.

C) Classify the bug as one of the following:

  1. >> Show Stopper <<
2. Medium Priority
3. Cosmetic
4. Low Priority

D) Application Version and Platform:

Version
    SimpleIDE 0-9-73

Platform

Choose OpSys from Labels Below:
    OpSys-All, OpSys-Linux, OpSys-Mac, or >> OpSys-Windows <<

Specify Platform OS Version and 32 or 64 bit. For example:

Linux Debian (32 or 64 bit)
Linux Suse   (32 or 64 bit)
Mac OSX      (64 bit Lion)
Windows XP   (32 bit)
    >> Windows 7    (32 or 64 bit) <<

Provide any links or additional information below if possible.


```

Original issue reported on code.google.com by `parallax...@gmail.com` on 19 Sep 2014 at 8:24

**Comment by AndyLindsay** [comment]
I'm seeing the same symptoms again on Windows 10.  Should I reopen this issue or create a new one?

**Comment by jsdenson** [comment]
What version?  I'm running 1.1.2.
I'll support critical reproducible bugs no problem.

**Comment by AndyLindsay** [comment]
Sounds good.  

All are running 1.1.0 on native Windows OS.  One reports on Windows 10, and one on Windows 7.  I verified the Windows 10 report on a second native Windows OS.

Note: SimpleIDE 1.1.0, was downloaded from [here](https://www.parallax.com/downloads/simpleide-propeller-c-software-windows).

**Comment by jsdenson** [comment]
Please use 1.1.2 which I notified parallax about in the summer. I don't
have any print dialog problems with it on Windows 10.
Version 1.1.2 was posted to fix the ParallaxInc registry clobbering problem.

**Comment by AndyLindsay** [comment]
Okay, thanks.  I'll check it out.
