### ISSUE TITLE
Problem with FIND operations

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/propside#249]
This is from a customer who directly emailed us:

The FIND command is flawed to the point of irritation, at least on my machine (Windows 7).  When FIND is successful, the IDE "loses focus," meaning that you need to click on the screen, on the highlighted word in order to make a modification.  More common behavior (all Microsoft compilers, for example) is to leave word highlighted and selected, ready for modification and not force an additional click to make things work.  Thanks, and I hope that makes sense.

**Comment by jsdenson** [comment]
Will make editor have focus after closing Find/Replace dialog.

**Comment by PropGit** [comment]
UPDATE: Should work properly in v1.0.54. Needs testing.

**Comment by PropGit** [comment]
Verified fixed in v1.0.54.
