### ISSUE TITLE
Increase contrast on "found" item

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/propside#251]
It would be wonderful if the Find feature used a greater contrast color for highlighting the found item.

**Comment by jsdenson** [comment]
Will make find text yellow highlighted while Find/Replace dialog is open.

**Comment by PropGit** [comment]
UPDATE: Should work properly in v1.0.54. Needs testing.

**Comment by PropGit** [comment]
Verified fixed in v1.0.54.
