### ISSUE TITLE
SimpleIDE 1.0.50 uses old Simple Libraries folder; we'll be using a Simple-Libraries Master branch from here forward

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/propside#257]
SimpleIDE 1.0.50 is using an old and outdated version of the Simple Libraries folder.  

Also, moving forward, we'll be using the master branch of [Simple-Libraries](https://github.com/parallaxinc/Simple-Libraries).

Steps:
0) Close SimpleIDE if it's open
1) Delete the workspace folder (typically SimpleIDE in ...Documents).  
2) Open SimpleIDE and follow the prompts to workspace folder creation.
3) Open Update Your Learn Folder.html, from the workspace folder's Learn subdirectory, and check the Update History.  The default location is "...Documents\SimpleIDE\Learn\Update Your Learn Folder.html" 

If the update history matches the corresponding file in the Simple-Libraries Master branch, chances are good it's correct.  If the Update History in that file doesn't reflect a recent change it's probably the wrong one.

**Comment by PropGit** [comment]
__jsdenson reports:__ Already fixed for libraries available in that time frame.

**Comment by PropGit** [comment]
@jsdenson - Does that mean the next build will include that latest Simple Libraries from the current master branch?

**Comment by jsdenson** [comment]
Yes, the latest will be pulled at build time.


Best Regards,
--Steve

**Comment by PropGit** [comment]
@jsdenson - Awesome.  Thank you!
