### ISSUE TITLE
SimpleIDE Terminal v1.0.51 wraps to window when set to page

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/propside#258]
SimpleIDE Terminal wraps to window when set to wrap to page.  

Run this code using Run with Terminal.

`#include "simpletools.h"

int main()
{

  char s[] = "0123456789";
  for(int i = 0; i < 8 \* 2; i++)
  {
    print("%s", s);
  }    

  while(1);  
}`

Try sizing the window to something larger than 80.  At this size, it correctly wraps text at the expected 80 characters, which is the default.  

![2016-09-01_13-14-48](https://cloud.githubusercontent.com/assets/11575415/18182784/432dc850-7046-11e6-80e0-6a4278f421a7.png)

Then, try sizing the window to something below 80 and re-run the program.  The output will look something like this: 

![2016-09-01_13-22-11](https://cloud.githubusercontent.com/assets/11575415/18183604/fe3f3b62-7049-11e6-9013-d8f4337a708b.png)

The expected result is more what we see in Parallax Serial Terminal with Wrap Text to (page) and Page Width set to 80:

![2016-09-01_13-45-45](https://cloud.githubusercontent.com/assets/11575415/18183709/7654eab6-704a-11e6-91cf-9fc617cfe79f.png)

**Comment by jsdenson** [comment]
We can add no line wrap setting as default to the terminal which would make the result more like what you want, but I can't guarantee the behavior you want to achieve.

Assuming this is acceptable, would you like no line wrap to be the default? Making "line wrap" an option requires more code and will change the options interface, and increases risk/delivery schedule.

**Comment by PropGit** [comment]
__jsdenson reports:__ Already fixed.

**Comment by PropGit** [comment]
Verified fixed in v1.0.53.
