### ISSUE TITLE
Variables set to CNT need to be volatile?

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/propside#263]
We've found a behavior recently where variables set equal to CNT did not work without the variables being volatile.  We suspect it's "proper" behavior, from the C standpoint, but have never seen it before, until just recently.

Is this proper?

**Comment by jsdenson** [comment]
CNT can change without the program's knowledge and therefore any reference
to it must be volatile.


Best Regards,
--Steve

**Comment by PropGit** [comment]
Even just taking a snapshot of the value of CNT requires that the storage (variable) for the snapshot being volatile?  I can't understand why that would be a requirement on an atomic element like a LONG.

**Comment by PropGit** [comment]
Closing this ended discussion.
