### ISSUE TITLE
SimpleIDE Windows Installer nukes all other Parallax software registry settings

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/propside#281]
The SimpleIDE Windows Installer (at least v1.1.0) completely wipes all the registry keys from Computer\HKEY_CURRENT_USER\Software\ParallaxInc before inserting it's SimpleIDE key.

This, of course, makes all other Parallax software behave as if it had just been freshly installed.  Bad behavior.

**Comment by jsdenson** [comment]
SimpleIDE should only be removing SimpleIDE keys. Please verify.

**Comment by PropGit** [comment]
I verified it myself after it was reported to me by a customer.

- Install and run BASIC Stamp Editor, Propeller IDE, Propellent, etc.
- Look at Computer\HKEY_CURRENT_USER\Software\ParallaxInc\ using Regedit
- Install SimpleIDE v1.1.0
- Refresh view of Computer\HKEY_CURRENT_USER\Software\ParallaxInc\
  - The ParallaxInc folder in the hive is now gone; the installer removed it

Before:
![image](https://cloud.githubusercontent.com/assets/1266318/23924983/55437644-08ca-11e7-8435-656f3241a5f4.png)

After:
![image](https://cloud.githubusercontent.com/assets/1266318/23924985/590dd68e-08ca-11e7-9bfc-c9e811f49000.png)

**Comment by JonMcPhalen** [comment]
I can confirm this -- has been going on for a very long time. Same bug affects PropellerIDE.

**Comment by jsdenson** [comment]
I was looking at this issue today. The 1.1.0/1.1.1 installer has an uninstall statement to remove publisher. Whether that is actually used in the install is unknown. I'll release 1.1.2 to remove the statement.
